# Generated by Django 6.0.1 on 2026-08-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leetcode_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('difficulty', models.CharField(max_length=20)),
                ('acceptance_rate', models.FloatField(blank=True, null=True)),
                ('topics', models.JSONField(default=list)),
            ],
        ),
    ]
